name: Hello Action
on: [push]

jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
    - name: hello
      id: hello
      uses: PeerXu/hello-action
      with:
        name: "Peer"
    - name: hello-output
      run: |
        echo ${{ steps.hello.outputs.greeting }}
